# Generated by Django 5.1.1 on 2024-09-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('financas', '0001_initial'),
        ('metodopagamento', '0001_initial'),
        ('recorrencia', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='metodo_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metodopagamento.metodopagamento'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='recorrencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recorrencia.recorrencia'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
