# Generated by Django 5.1.1 on 2024-09-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorrencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorrencia',
            name='intervalo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
